<?php $this->headTitle("Residential Roofer Chicago | Shingle and Flat Roof Replacement - Second City Roofing &amp; Construction"); ?>

<section class="page-sub">
    <div class="page page-content">
        <div class="content-sub">
            <h1>Full-Service Roofing & Construction Company Chicago, IL</h1>
            <h3>Call us at (773) 384-6300 to speak with one of our professionals today!</h3>
            <div class="content section group">
                <div class="col col-left">
                    <h2>About Us</h2>
                    <strong>Second City Roofing & Construction is a family-owned and operated roofing and home improvement company that has been serving Chicagoland for over 37 years.</strong> Founder and owner Ed Baker has work extremely hard to establish Second City as Chicagoland's first choice in home improvement companies.
                    <br/><br/>
                    <strong>We are confident that nobody will do a better job for less... nobody!</strong>
                    <br/><br/>
                    We at Second City have earned our stellar reputation by building long-lasting relationships based on trust and dedicated commitment to our customers. We pay close attention to our customers' needs and provide them with quality work at affordable prices. We stand behind our work and our commitment to excellent service continues to earn our company an <strong>“A+” rating with the Better Business Bureau and Four Star Rating With Yelp.</strong>
                    <br/><br/>
                    As a fully licensed, bonded and insured home improvement contractor, Second City Roofing & Construction strives to provide customers with the peace of mind they deserve throughout every project.
                    <br/><br/>
                    <strong>Call us today at 773-384-6300 for a free in home consultation</strong> so that we may begin providing you with the best value, best service, and warranty for the highest quality roofing and home improvement in Chicagoland.
                </div>
                <div class="col col-right">
                    <img src="<?=$this->basepath('img/payment.jpg')?>" />
                    <div class="col-right-box">
                        <b>Fully Licensed, Bonded & Insured</b><br/>
                        State of Illinois Roofing Lic: #104.013526<br/>
                        City of Chicago GC Lic: #GC04529-6<br/>
                        City of Chicago Home Repair Lic: #18818<br/>
                        <br/>
                        We are licensed in Chicago and
                        most Chicagoland suburbs.
                    </div>
                    <div class="col-right-box">
                        <b>Second City Roofing & Construction</b><br/>
                        3006 West Diversey Avenue<br/>Chicago, IL 60647 <br/>
                        Call Now for an Estimate: 773-384-6300 <br/>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
