<?php $this->headTitle("Exterior Remodeling Contractor in Chicago area - Second City Roofing &amp; Construction"); ?>

<section class="page-sub">
    <div class="page page-content">
        <div class="content-sub">
            <h1>Chicago Exterior Remodeling & Upgrades</h1>
            <h3>Call us at (773) 384-6300 to speak with one of our professionals today!</h3>
            <div class="content section group">
                <div class="col col-left">
                    <h2>Second City is an experienced and trusted contractor providing a full range of tuckpointing services.</h2>
                    <br/><br/>
                    <div class="service">
                        <img src="<?=$this->basepath('img/icon_masonry.png')?>" title="Tuckpointing Services" alt="Tuckpointing Services" />
                        <h4><a name="masonry">Tuckpointing Services</a></h4>
                        We pay close attention to detail and always display the best workmanship possible. After the job is finished, we perform a detailed clean-up of the site, leaving the area as close to the way we found it as possible.
                    </div>
                    <br/>
                    <div class="service">
                        <img src="<?=$this->basepath('img/icon_chimney.png')?>" title="Chimney Repair & Restoration" alt="Chimney Repair & Restoration" />
                        <h4><a name="chimney">Chimney Repair & Restoration</a></h4>
                        Chimney repair can be anything from a good tuckpoint to a total rebuild. Our expert technicians can certainly determine the right solution. We will also check the condition of your chimney liner, which we can replace, if necessary.
                    </div> 
                    <br/>
                    <div class="service">
                        <img src="<?=$this->basepath('img/icon_siding.png')?>" title="Siding" alt="Siding" />
                        <h4><a name="siding">Siding</a></h4>
                        We install high-quality, high-efficiency siding with insulation in many colors and designs.
                    </div>
                    <br/>
                    <div class="service">
                        <img src="<?=$this->basepath('img/icon_gutters.png')?>" title="Soffit & Fascia Work" alt="Soffit & Fascia Work" />
                        <h4><a name="gutters">Soffit & Fascia Work</a></h4>
                        Tired of painting your overhangs? Second City can cover them with aluminum or vinyl energy-saving products in many colors.<br/><br/>
                        <h4>Gutters & Downspouts</h4>
                        Certainly now that you’re considering your roof now is the best time to check your gutters & downspouts. We offer aluminum & galvanized gutter systems in many different sizes & colors..
                    </div> 
                    <br/>
                    <div class="service">
                        <img src="<?=$this->basepath('img/icon_windows.png')?>" title="Replacement Windows" alt="Replacement Windows" />
                        <h4><a name="windows">Replacement Windows</a></h4>
                        Energy concious? This is the root of all evil. Second City can replace the windows in your house easily and inexpensively with highly energy-efficient windows in many many styles and many many colors.
                    </div>
                    <br/>
                    <div class="service">
                        <img src="<?=$this->basepath('img/icon_doors.png')?>" title="Replacement Doors" alt="Replacement Doors" />
                        <h4><a name="doors">Replacement Doors</a></h4>
                        Are you energy-concious as well as security-concious? Second City offers a vast array of replacement doors, steel security doors & storm doors. We offer numerous styles & colors.
                    </div>
                    <br/>
                    <div class="service">
                        <img src="<?=$this->basepath('img/icon_porches.png')?>" title="Porch & Deck Services" alt="Porch & Deck Services" />
                        <h4><a name="porch">Porch Services</a></h4>
                        Second City Roofing & Construction not only builds sturdy porches for an affordable price, but we specialize in code violations!<br/><br/>
                        If you are in the Chicago area and you are looking to invest in a new porch, call us!
                    </div><br/>
                    <div class="service">
                        <img src="<?=$this->basepath('img/icon_fencing.png')?>" title="Fencing" alt="Fencing" />
                        <h4><a name="fencing">Fencing</a></h4>
                        <b>Security, Security, Security, Security.</b><br/>
                        Need we say more? Second City offers wrought iron, combination wrought iron & wood, wood, chain link and vinyl fencing. Our fencing can add beauty and value to your home as well.
                    </div>
                    <br/>
                    <div class="service">
                        <img src="<?=$this->basepath('img/icon_awnings.png')?>" title="Awnings" alt="Awnings" />
                        <h4>Awnings</h4>
                        Add Second City’s awnings to cover doors and windows. We'll come to your home to help you choose the right product to provide maximum shade protection.
                    </div>
                    
                </div>
                <div class="col col-right">
                    <img src="<?=$this->basepath('img/payment.jpg')?>" />
                    <div class="col-right-box">
                        <b>Fully Licensed, Bonded & Insured</b><br/>
                        State of Illinois Roofing Lic: #104.013526<br/>
                        City of Chicago GC Lic: #GC04529-6<br/>
                        City of Chicago Home Repair Lic: #18818<br/>
                        <br/>
                        We are licensed in Chicago and
                        most Chicagoland suburbs.
                    </div>
                    <div class="col-right-box">
                        <b>Second City Roofing & Construction</b><br/>
                        3006 West Diversey Avenue<br/>Chicago, IL 60647 <br/>
                        Call Now for an Estimate: 773-384-6300 <br/>
                    </div> 
                    <div class="guy">
                        <p><b>Did you know?</b><br/>
                            The City of Chicago Department of Buildings requires your porch to hold a minimum of 100 lbs. per sqare foot.</p>
                            <br/><br/><br/><br/><br/>
                        <a href="<?=$this->basepath('chicago-roofing-estimate-quote/')?>"><img src="<?=$this->basepath('../img/button_side_contact.gif')?>" /></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>