<?php $this->headTitle("Professional Masonry Services - Second City Roofing"); ?>

<section class="page-sub page-sub-lp">
    <div class="page page-content">
        <div class="content-sub content-sub-lp1">
					<div class="content-sub-lp1-block1">
                <div>
                  <p>Family Owned and Operated<br/>For Over 35 Years</p>
                </div>
								
						<div class="content-sub-lp1-block1-col1">
                        <div class="free-Estimate"><a href="#" onclick="fsLightbox2356097.show()" ID="light-box_link">FREE ESTIMATE</a></div>
                        	<a href="#"><img src="<?=$this->basepath('img/masonryLeftImg.png')?>" /></a>
                        </div>
						<div class="content-sub-lp1-block1-col2">
							<div class="content-sub-lp1-block1-col2-row1">
								<p>Our 37th Anniversary Sale!</p>
							</div>
							<div class="content-sub-lp1-block1-col2-row2">
								<p><span>$300 off</span></p> 
								<p><span>ANY PROJECT</span><br /><span>with this estimate!*</span></p>
							</div>
							<div class="content-sub-lp1-block1-col2-row3">
								<p><img src="<?=$this->basepath('img/lp-licensed.png')?>" /></p> 
								<p><img src="<?=$this->basepath('img/lp-bonded.png')?>" /></p> 
								<p><img src="<?=$this->basepath('img/lp-insured.png')?>" /></p> 
							</div>
							<div class="content-sub-lp1-block1-col2-row4">					
								<div>
									<div>
										<p style="margin-bottom: 10px;"><b style="color:#e16819; text-transform:uppercase;">ALL KINDS</b> of Masonry <br />
											and Tackpointing Work</p>
										<p>Includes <b>BRICK REPAIR </b><br />
											<b>and RESTORATION</b></p>
									</div>
									<div><img src="<?=$this->basepath('img/lp-vertical-divider.png')?>" /></div>
									<div class="clr"></div>
								</div>
								<div>
									<div>
										<p style="margin-bottom: 10px;"><b style="color:#629600;text-transform:uppercase;">Easy Financing</b> <br />
											Many plans to choose from,  <br />
											tailor-made to fit your budget.</p>

										<p>No Money Down FHA  <br />
											Improvement Loans.
											</p>		
									</div>
									<div><img src="<?=$this->basepath('img/lp-vertical-divider.png')?>" /></div>
									<div class="clr"></div>	
								</div>
								<div>
									<div>
										<p style="margin-bottom: 10px;"><b style="color:#e16819;text-transform:uppercase; ">All-IN-ONE</b> <br />
											Low Monthly Payment</p>
										<p><b>PERMIT</b> and a convenient <br />
											<b>FINANCING PROGRAM.</b></p>								
									</div>	
								</div>
							</div>
						</div>
						<div class="clr"></div>
					</div>
					<div class="content-sub-lp1-block2 requestcontact">
					<div class="form_first_area">	
							<p>Free Estimate - No Money Down</P>
							<p>FINANCING AVAILABLE</P>
							<hr />
							<p>Se habla Español.</P>
							<a onclick="fsLightbox2356097.show()" ID="light-box_link">REQUEST CONTACT</a>
                        	<p>FREE NO OBLIGATION IN-HOME ESTIMATE</p>                        
						</div>	
						<div class="form_second_area">
							<h3>Free Estimate</h3>
							<input type="text" name=""  placeholder="Name" class="user_name"/>
							<input type="text" name=""  placeholder="Phone Number" class="phone_number"/>
							<input type="submit" name="" value="SUBMIT"  class="submit m_submit"/>
						</div>							
						<div class="form_third_area">
							<h3>THANK YOU!</h3>
							<p id="message" class="message">Your message has been succesfully sent. We will contact you very soon!</p>
						</div>						
					</div>
					<div class="content-sub-lp1-block3"><a href="#">
						<img src="<?=$this->basepath('img/lp-content-left-img-mobile.png')?>" /></a>
					</div>
					<div class="content-sub-lp1-block4">					
						<div>
							<div>
								<p><b style="color:#e16819; text-transform:uppercase;">ALL KINDS</b> of Shingles <br />
									& Flat Rubber Roofs</p><br>
<br>

								<p>Includes <b>WATER & ICE <br />
									SHIELD</b> on <b>ALL <br />
									TEAR-OFFS.</b></p>	
							</div>
						</div>
						<div>
							<div>
								<p><b style="color:#629600;text-transform:uppercase;">Easy Financing</b> <br />
									Many plans to choose from,  <br />
									tailor-made to fit your budget.</p><br><br>


								<p>No Money Down FHA  <br />
									Improvement Loans.
									</p>		
							</div>
						</div>
						<div>
							<div>
								<p><b style="color:#e16819;text-transform:uppercase; ">All-IN-ONE</b> <br />
									Low Monthly Payment</p><br><br>


								<p><b>PERMIT</b> and a convenient <br />
									<b>FINANCING PROGRAM.</b></p>								
							</div>	
						</div>
					</div>
                    <div style="clearfix"></div>
        </div>
        <div style="clearfix"></div>
		<div class="content-sub content-sub-lp2">
			<p>
			SAVE HUNDRED$ even THOU$AND$ during this GREAT $ALE!
			</p>
		</div>
    </div>
	
</section>

<section class="carousel-lp">
	<div class="page">
    <div id="trust" class="owl-carousel trust trust-lp">
        <div><img src="<?=$this->basepath('img/icon_bbb.png')?>" /></div>
        <div><img src="<?=$this->basepath('img/icon_yelp.png')?>" /></div>
        <div><img src="<?=$this->basepath('img/icon_angie.png')?>" /></div>
        <div><img src="<?=$this->basepath('img/icon_tv.png')?>" /></div>
        <div><img src="<?=$this->basepath('img/icon_certainTeed.png')?>" /></div>
        <div><img src="<?=$this->basepath('img/icon_google.png')?>" /></div>
    </div>
    <script>
    $(document).ready(function() {
        $("#trust").owlCarousel({
            pagination : false, items : 6, itemsDesktop : [1199,6], itemsDesktopSmall : [960,4], itemsTablet : [768,4], itemsTabletSmall : [700,3], itemsMobile : [500,2]
        });
    });
    </script>
        </div>
</section>


<section class="footer footer-lp">
    <div class="page">
       <div class="footer-right footer-right-lp">
            <div class="social">
            <ul>
				<li><a href="#"><img src="<?=$this->basepath('img/lp-improve_now_pay_later.png')?>" /></a></li>
		<!--
        <li><a href="#"></a><img src="<?=$this->basepath('img/icon-google.png')?>" /></li> -->
    </ul>
    </div>
</div>

<script>
$(function () {
    $('.go-to-top').click(function () {
        $('html,body').animate({
            scrollTop: 0
        }, 500);
    return false;
    });
});
</script>

<div class="copy">
    <p style="font-size: 13px; color: #383838;">
    * Limited time offer. Valid until <?=date("m")?>/30/2016. Project based on $3000 or more. Must mention this promotion at time of estimate. Not valid prior sales or other promotions.    
    <br/><br/>
    
    <img src="http://www.secondcityconstruction.com/img/owner.jpg" style="margin-right: 15px; width: 150px; float: left;" /><b>Second City Roofing and Exteriors</b> has been taking care of the roofs in Chicagoland for over 45 years with their affordable yet effective and reliable masonry services. We can handle all your housing repair and improvement needs and there’s nothing to worry about your house’s safety as our company is fully licensed, insured and bonded.<br/><br/>
            <b>Masonry Experts</b><br/>
            We are leading in providing only excellent <b>masonry services</b> to our clients with the most reasonable prices and we only give out the best standards of quality.  Our business understands the importance of a good masonry in the structural integrity of a building and we make sure that our Chicago clients only get the best masonry for their homes that can stand any weather condition.<br/><br/> 
            Our teams of workers are highly skilled and well experienced in using a wide variety of materials using the state-of-the-art technology to make your home safe, sturdy and good looking. We give out a full manufacturer’s warranty on each product that we used.<br/><br/>
            <b>Residential Masonry in Chicago</b><br/>
            Our professional workers will closely work with you for them to completely understand what are your needs, your requirements and your budget. We can create a good and fully personalized estimate depending on the information you are going to provide. We are accepting all kinds of masonry and tackpointing work which includes brick repair and restoration.<br/><br/> 
            Aside from the free estimates, we also provide easy financing options for our Chicago customers from custom made to what is best to your budget. We offer no money down for FHA improvement loans.  Call our number today at (773) 384-6300 and we will assure you of a better home tomorrow. We can improve your home now and pay us later! For your convenience, we are accepting all major credit cards.
                         
        </div>
		<div class="clr"></div>
    </div>
</section>
        
        
<!-- Begin Lightbox -->
<div id="fsLightbox2356097" class="fsLightbox" style="display:none;">
    <div align="right" style="padding-bottom:5px;">
        <a id="fsLightboxClose2356097" href="#" title="close"><img src="https://storsky.formstack.com/forms/images/2/cross.gif" border="0" /></a>
    </div>
    <div id="fsLightboxContent2356097" style="height:450px; width:650px; padding-top:0px; overflow:auto;">
        <script type="text/javascript" src="https://storsky.formstack.com/forms/js.php/scr_request_qote"></script>
        
    </div>
</div>

<!--<a onclick="fsLightbox2356097.show()" ID="light-box_link">Link for REQUEST CONTACT - delete after you use it!</a>-->

<script type="text/javascript" src="https://storsky.formstack.com/forms/js/lightbox.js"></script>
<script type="text/javascript">
    var fsLightbox2356097 = new FSLightbox({
        form: 2356097,
        handleText: "CONTACT US",
        handlePosition: "left",
        handleImage: "https://storsky.formstack.com/forms/lightboxHandle.php?str=Contact+Form",
        handle: null
    });
</script>
<!-- Use fsLightbox2356097.show() or set handle: "ID" to open lightbox without using predefined handle -->
<!-- End Lightbox -->


<!--<br/><br/>
<a class="wistia-popover[height=388,playerColor=7b796a,width=640]" href="//fast.wistia.net/embed/iframe/2xj73kgeg8?popover=true" style="width: 960px; height: 327px; top: 0px; left: 0px;" jssor-content="true">LINK FOR TOP VIDEO - REMOVE AFTER YOU DONE</a>-->
<script charset="ISO-8859-1" src="//fast.wistia.com/assets/external/popover-v1.js"></script>


