<?php $this->headTitle("Professional Siding Company - Second City Roofing"); ?>

<section class="page-sub page-sub-lp">
    <div class="page page-content">
        <div class="content-sub content-sub-lp1">
					<div class="content-sub-lp1-block1">
                <div>
                  <p>Family Owned and Operated<br/>For Over 35 Years</p>
                </div>
								
						<div class="content-sub-lp1-block1-col1">
                        <div class="free-Estimate"><a href="#"  onclick="fsLightbox2356097.show()" ID="light-box_link">FREE ESTIMATE</a></div>
                        	<img src="<?=$this->basepath('img/sidingLeftImg.png')?>" />
                        </div>
						<div class="content-sub-lp1-block1-col2">
							<div class="content-sub-lp1-block1-col2-row1">
								<p>Our 37th Anniversary Sale!</p>
							</div>
							<div class="content-sub-lp1-block1-col2-row2">
								<p><span>$300 off</span></p> 
								<p><span>ANY PROJECT</span><br /><span>with this estimate!*</span></p>
							</div>
							<div class="content-sub-lp1-block1-col2-row3">
								<p><img src="<?=$this->basepath('img/lp-licensed.png')?>" /></p> 
								<p><img src="<?=$this->basepath('img/lp-bonded.png')?>" /></p> 
								<p><img src="<?=$this->basepath('img/lp-insured.png')?>" /></p> 
							</div>
							<div class="content-sub-lp1-block1-col2-row4">					
								<div>
									<div>
										<p style="margin-bottom: 10px;"><b style="color:#e16819; text-transform:uppercase;">ALL KINDS</b> of Siding <br />
						                      installation and repair</p>
						                    <p>Includes <b>SOFFIT <br />
						                      FASCIA, GUTTERS, <br />
						                      GUTTERS WORK</b></p>  
									</div>
									<div><img src="<?=$this->basepath('img/lp-vertical-divider.png')?>" /></div>
									<div class="clr"></div>
								</div>
								<div>
									<div>
										<p style="margin-bottom: 10px;"><b style="color:#629600;text-transform:uppercase;">Easy Financing</b> <br />
											Many plans to choose from,  <br />
											tailor-made to fit your budget.</p>
										<p>No Money Down FHA  <br />
											Improvement Loans.
											</p>		
									</div>
									<div><img src="<?=$this->basepath('img/lp-vertical-divider.png')?>" /></div>
									<div class="clr"></div>	
								</div>
								<div>
									<div>
										<p style="margin-bottom: 10px;"><b style="color:#e16819;text-transform:uppercase; ">All-IN-ONE</b> <br />
											Low Monthly Payment</p>
										<p><b>PERMIT</b> and a convenient <br />
											<b>FINANCING PROGRAM.</b></p>								
									</div>	
								</div>
							</div>
						</div>
						<div class="clr"></div>
					</div>
					<div class="content-sub-lp1-block2 requestcontact">
					<div class="form_first_area">	
							<p>Free Estimate - No Money Down</P>
							<p>FINANCING AVAILABLE</P>
							<hr />
							<p>Se habla Español.</P>
							<a onclick="fsLightbox2356097.show()" ID="light-box_link">REQUEST CONTACT</a>
	                        	<p>FREE NO OBLIGATION IN-HOME ESTIMATE</p>
						</div>	
						<div class="form_second_area">
							<h3>Free Estimate</h3>
							<input type="text" name=""  placeholder="Name" class="user_name"/>
							<input type="text" name=""  placeholder="Phone Number" class="phone_number"/>
							<input type="submit" name="" value="SUBMIT"  class="submit m_submit"/>
						</div>							
						<div class="form_third_area">
							<h3>THANK YOU!</h3>
							<p id="message" class="message">Your message has been succesfully sent. We will contact you very soon!</p>
						</div>						
					</div>
					<div class="content-sub-lp1-block3"><a href="#">
						<img src="<?=$this->basepath('img/lp-content-left-img-mobile.png')?>" /></a>
					</div>
					<div class="content-sub-lp1-block4">					
						<div>
							<div>
								<p><b style="color:#e16819; text-transform:uppercase;">ALL KINDS</b> of Shingles <br />
									& Flat Rubber Roofs</p><br>
<br>

								<p>Includes <b>WATER & ICE <br />
									SHIELD</b> on <b>ALL <br />
									TEAR-OFFS.</b></p>	
							</div>
						</div>
						<div>
							<div>
								<p><b style="color:#629600;text-transform:uppercase;">Easy Financing</b> <br />
									Many plans to choose from,  <br />
									tailor-made to fit your budget.</p><br><br>


								<p>No Money Down FHA  <br />
									Improvement Loans.
									</p>		
							</div>
						</div>
						<div>
							<div>
								<p><b style="color:#e16819;text-transform:uppercase; ">All-IN-ONE</b> <br />
									Low Monthly Payment</p><br><br>


								<p><b>PERMIT</b> and a convenient <br />
									<b>FINANCING PROGRAM.</b></p>								
							</div>	
						</div>
					</div>
                    <div style="clearfix"></div>
        </div>
        <div style="clearfix"></div>
		<div class="content-sub content-sub-lp2">
			<p>
			SAVE HUNDRED$ even THOU$AND$ during this GREAT $ALE!
			</p>
		</div>
    </div>
	
</section>

<section class="carousel-lp">
	<div class="page">
    <div id="trust" class="owl-carousel trust trust-lp">
        <div><img src="<?=$this->basepath('img/icon_bbb.png')?>" /></div>
        <div><img src="<?=$this->basepath('img/icon_yelp.png')?>" /></div>
        <div><img src="<?=$this->basepath('img/icon_angie.png')?>" /></div>
        <div><img src="<?=$this->basepath('img/icon_tv.png')?>" /></div>
        <div><img src="<?=$this->basepath('img/icon_certainTeed.png')?>" /></div>
        <div><img src="<?=$this->basepath('img/icon_google.png')?>" /></div>
    </div>
    <script>
    $(document).ready(function() {
        $("#trust").owlCarousel({
            pagination : false, items : 6, itemsDesktop : [1199,6], itemsDesktopSmall : [960,4], itemsTablet : [768,4], itemsTabletSmall : [700,3], itemsMobile : [500,2]
        });
    });
    </script>
        </div>
</section>


<section class="footer footer-lp">
    <div class="page">
       <div class="footer-right footer-right-lp">
            <div class="social">
            <ul>
				<li><a href="#"><img src="<?=$this->basepath('img/lp-improve_now_pay_later.png')?>" /></a></li>
		<!--
        <li><a href="#"></a><img src="<?=$this->basepath('img/icon-google.png')?>" /></li> -->
    </ul>
    </div>
</div>

<script>
$(function () {
    $('.go-to-top').click(function () {
        $('html,body').animate({
            scrollTop: 0
        }, 500);
    return false;
    });
});
</script>

<div class="copy">
    <p style="font-size: 13px; color: #383838;">
    * Limited time offer. Valid until <?=date("m")?>/30/2016. Project based on $3000 or more. Must mention this promotion at time of estimate. Not valid prior sales or other promotions.    
    <br/><br/>
    
    <img src="http://www.secondcityconstruction.com/img/owner.jpg" style="margin-right: 15px; width: 150px; float: left;" />Are you eyeing for an expert and <em>experienced siding company</em>?<br/><br/>
    Has some parts of your siding begun to corrode while the rest is still good? Loose-fitting soffits can create bothersome clatters when the wind blows. If your siding has developed a white scum or is washed-out, discolored or just plain the wrong color, fear not.  <b>Broken siding is no reason for misery</b>. <br/><br/>
    Look no further than <b>Second City Roofing and Exteriors</b>, a family owned and operated leader in siding installation and services. Our professional contractors get the job done right using the top class resources and the most steadfast systems. Our contractors are trained and qualified on installation and repair.<br/><br/>
    With 37 years of experience, which allowed us to have wide-ranging capability, supplier contacts, as well as a solid base of <b>happy and satisfied customers</b>, we offer high quality workmanship with the up-to-the-minute innovations. We can help you create your home’s exterior design and décor dreams come to life! Whatever your needs or budget, we’ve got you covered!<br/><br/> 
    We do <b>all kids of siding installation and repair</b> including but not limited to <u>soffit, fascia, gutters and gutter work</u>. We have low monthly payments, permit and a convenient financing program. You have many plans to choose from. It could be tailor-made to fit your budget. <br/><br/>
    On our 37th anniversary, we offer <u>$300 off on any project with $3000</u> or more estimate. 	Just mention this promotion at the time of estimate to take advantage of the offer.<br/><br/> 
    Upgrading or renovating the siding of your home is not only a practical way of a safety measure of your residence but also a substantial economic investment as well. We work with you to safeguard both your home and pocket. Our skilled team uses only established, fail-safe products and supplies with inclusive warranties. <b>No job is too big or too small for us</b>.<br/><br/>
    Our home improvement experts will be more than happy to explain out variety of selection of services, answer any queries and meet with you for a one on one obligation free quote. <i>We accept Visa, Mastercard, American Express and Discover</i>. Call us at (773) 384 6300 for an estimate.<br/><br/>
                         
        </div>
		<div class="clr"></div>
    </div>
</section>


<!-- Begin Lightbox -->
<div id="fsLightbox2356097" class="fsLightbox" style="display:none;">
    <div align="right" style="padding-bottom:5px;">
        <a id="fsLightboxClose2356097" href="#" title="close"><img src="https://storsky.formstack.com/forms/images/2/cross.gif" border="0" /></a>
    </div>
    <div id="fsLightboxContent2356097" style="height:450px; width:650px; padding-top:0px; overflow:auto;">
        <script type="text/javascript" src="https://storsky.formstack.com/forms/js.php/scr_request_qote"></script>
        
    </div>
</div>

<!--<a onclick="fsLightbox2356097.show()" ID="light-box_link">Link for REQUEST CONTACT - delete after you use it!</a>-->

<script type="text/javascript" src="https://storsky.formstack.com/forms/js/lightbox.js"></script>
<script type="text/javascript">
    var fsLightbox2356097 = new FSLightbox({
        form: 2356097,
        handleText: "CONTACT US",
        handlePosition: "left",
        handleImage: "https://storsky.formstack.com/forms/lightboxHandle.php?str=Contact+Form",
        handle: null
    });
</script>
<!-- Use fsLightbox2356097.show() or set handle: "ID" to open lightbox without using predefined handle -->
<!-- End Lightbox -->


<!--<br/><br/>
<a class="wistia-popover[height=388,playerColor=7b796a,width=640]" href="//fast.wistia.net/embed/iframe/2xj73kgeg8?popover=true" style="width: 960px; height: 327px; top: 0px; left: 0px;" jssor-content="true">LINK FOR TOP VIDEO - REMOVE AFTER YOU DONE</a>-->
<script charset="ISO-8859-1" src="//fast.wistia.com/assets/external/popover-v1.js"></script>


