<?php $this->headTitle("Affordable Roofing Services in Chicago - Second City Roofing"); ?>

<section class="page-sub">
    <div class="page page-content">
        <div class="content-sub">
            <h1>Affordable Roofing Services Chicago, IL</h1>
            <h3>Call us at (773) 384-6300 to speak with one of our professionals today!</h3>
            <div class="content section group">
                <div class="col col-left">
                    <h2>We are a full-service, licensed and insured roofing company serving Chicagoland for over 37 years. Let our trained roofing technicians inspect your roof to give you the answers.</h2><br/>
                    As a fully licensed, bonded and insured company, Second City Roofing & Construction is here to take care of all your roofing and home improvement needs. We assure you that once hired, we will take care of all your needs without you having to worry about a thing!
                    <br/><br/>
                    <strong>Chicago Roofing Experts</strong>
                    <br/>
                    Even in today's extremely competitive market, we have come out at the top for providing our clients with excellent services at the most reasonable prices. We believe in maintaining the highest standards of quality without ever compromising on the services we provide.<br/>
                    <br/>
                    At Second City Roofing & Construction, we understand the role a good roof plays in the structural integrity of any building and we want our customers to have the best homes in all of Chicago, which endure all kinds of weather. Our workers have years of experience and are skilled in using a variety of materials and the latest technology to make your home not only safe and stable but also good looking. We provide full manufacturer warranty on the products used.<br/>
                    <br/>
                    <strong>Residential Roofing in Chicago</strong>
                    <br/>
                    Our professionals work closely with you to fully understand your requirements, needs and budget. Based on the information you provide, we come up with an estimate that is tailored for each individual client. Ask us about our excellent financing options for our Chicago customers- you will not be disappointed. Give us a call today for a better home tomorrow!
                    <br/><br/>
                    <div class="service">
                        <img src="<?=$this->basepath('img/icon_shingle_roofs.png')?>" title="Shingle Roof" alt="Shingle Roof" />
                        <h4>Shingle Roofs</h4>
                        We do lay-overs & tear-offs using all types of shingles, depending on your needs and your price point. From the most basic 3-tab 10 year shingle to the finest architectual shingles available. All shingles have a manufacturer’s warrantees and Second City’s second-to-none labor warrantees.
                    </div>
                    <br/><br/>
                    <div class="service">
                        <img src="<?=$this->basepath('img/icon_flat_roofs_new.jpg')?>" title="Flat Roof" alt="Flat Roof" />
                        <h4>Flat Roofs</h4>
                        We do lay-overs & tear-offs using the highest-quality bitumen roofing with aluminum coating with many different thicknesses, again, depending on your needs and your price point. All of our flat roof work comes with manufacturer’s warrantees and Second City’s second-to-none labor warrantees.
                    </div>
                    <br/>
                    Find out more about <a href="<?=$this->basepath('roofing-101')?>">roofing types and shingles</a>.
                </div>
                <div class="col col-right">
                    <img src="<?=$this->basepath('img/payment.jpg')?>" />
                    <div class="col-right-box">
                        <b>Fully Licensed, Bonded & Insured</b><br/>
                        State of Illinois Roofing Lic: #104.013526<br/>
                        City of Chicago GC Lic: #GC04529-6<br/>
                        City of Chicago Home Repair Lic: #18818<br/>
                        <br/>
                        We are licensed in Chicago and
                        most Chicagoland suburbs.
                    </div>
                    <div class="col-right-box">
                        <b>Second City Roofing & Construction</b><br/>
                        3006 West Diversey Avenue<br/>Chicago, IL 60647 <br/>
                        Call Now for an Estimate: 773-384-6300 <br/>
                    </div> 
                    <div class="guy">
                        <p><b>Did you know?</b><br/>
                        A lot of what people might think are roof problems are really masonry problems. Our trained technicians will get to the source of either problem.</p>
                        <br/><br/><br/><br/><br/>
                        <a href="<?=$this->basepath('chicago-roofing-estimate-quote/')?>"><img src="<?=$this->basepath('../img/button_side_contact.gif')?>" /></a>
                    </div> 
                </div>
            </div>
        </div>
    </div>
</section>
