<?php $this->headTitle("Roofing 101"); ?>

<section class="page-sub">
    <div class="page page-content">
        <div class="content-sub">
            <h1>Roofing 101</h1><br/>
            
            <strong>Roof System Components</strong><br/>
            There are 5 basic components of a steep slope roof system. A step roof has a slope of at least 25 percent.<br/><br/>
			
			These components are:
			<ul class="content-ul">
				<li>1. <b>Roof covering</b>. This includes: shingles, tile, slate or metal and an underlayment that has the function of protecting the sheathing from exposure to weather conditions.</li>  
                <li>2. <b>Sheathing</b>. This consists of boards or sheet materials that are fastened to the rafters.</li>
                <li>3. <b>Roof structure</b>. This consists of rafters and trusses with a primary function of supporting  the sheathing</li>
                <li>4. <b>Flashing</b>. These consists of materials like sheet metal which are installed into a roof system’s joints and valleys to block the possibility of water seepage.</li>
                <li>5. <b>Drainage</b>. Refers to the part of a roof that guides the flow of water to the ground level. </li>
			</ul>
			<br/><br/>
			<img src="<?=$this->basepath('img/101.jpg')?>" alt="Roofing 101" title="Roofing 101" class="img-left" />			
			<h2>Selecting the appropriate roofing system</h2>			
			Several factors have to be considered in choosing the system that suits the roof of the house or building, including preferences and budget. These criteria includes: durability, aesthetics, architectural style and cost.<br/>
			<br/>
			When it comes to steep slope structures the following roofing products are on top of owners’ choices:<br/><br/>
			1.	<b>Asphalt shingles</b>. This accounts for a dominant portion of the U.S. steep slope roofing market. Contractors can use organic and fiberglass materials as reinforcement.<br/><br/> 
			Organic felts have been used as reinforcements for a period longer than the use of fiberglass. However, the current dominant practice is reinforcing asphalt with organic or fiberglass materials.<br/><br/> 
			<i>Organic shingles</i> is composed of cellulose fiber base (such as wood) which is mixed with asphalt and coated with color mineral granules.<br/><br/>
			On the other hand, <i>fiberglass shingles</i> is composed of a fiberglass mat, within a layer of asphalt at the top and bottom, mixed with mineral granules.<br/><br/>
			
			<h2>Fire Resistance</h2>
        	The resistance of asphalt shingles to fires are classified into three: class A, B, or C with Class A being the most fire-resistant.<br/><br/>
        	Most fiberglass shingles are rated as Class A, while most organic shingles are classified as Class C.<br/><br/>
			<img src="<?=$this->basepath('img/house-shingles.jpg')?>" alt="House with Roof Shingles" title="House with Roof Shingles" class="img-right" width="300" />        	
        	<h2>Appearance.</h2>
        	The reinforcement used in a shingle has a minimal effect on its appearance, since it is hidden from view.<br/><br/> 
        	Organic and fiberglass products appear textured since these are in laminated (architectural) grades, varying physical characteristics whatever be the reinforcement used and its appearance.<br/><br/>
        	It is recommended by NRCA that shingles comply with <a href="https://www.astm.org/" target="_blank">American Society for Testing Materials</a> (ASTM) particularly ASTM D 225 for organic shingles and ASTM D 3462 for fiberglass shingles.<br/><br/>
        	These standards cover the composition and physical properties of asphalt shingles. However, there are asphalt shingles being sold which do not comply with these standards. In case a shingle complies with one of these standards, the manufacturer’s product description and the product’s wrapper will cite this.<br/><br/>
        	Cedar, redwood, southern pine and other types of wood compose wood shingles and shakes. <br/><br/>
        	While wood shingles are sawn by machines, shakes are made by hand and look rougher.<br/><br/>
        	It is important to consider that there are local building codes which limit the use of wood shingles and shakes because of doubts on their resistance to fire. A Class C fire rating is attributed to many wood shingles and shakes. Sometimes, however, these do not have any fire rating. Note that certain wood shingle products incorporate fire-resistant treatment applied in the factory and are therefore rated as Class A.<br/><br/>
        	
        	<h2>Tile</h2> Title can either be clay or concrete. It is a durable roofing material. Different areas in the United States have varying preferences. In the Southwest and Florida, mission and Spanish-style round-topped tiles are used widely. However, flat styles are also available to create French and English looks.<br/><br/>
        	While tiles come in a variety colors and finishes, it is heavy. It is important that you verify first whether the structure can support the load in case you will be using tiles on a different roofing system.<br/><br/> 
        	<h2>Slate</h2> Slate is quarried in several areas such as in Vermont, Virginia, Pennsylvania and New York. Depending on its origin, state is available in different colors and grades. It is considered to be almost indestructible. However, it is more expensive than other roofing materials. Also, to be able to apply it well requires special skill and experience. Slate, a long lasting roofing material, to this day, still protects many old homes especially in the Northeast.<br/><br/> 
	
        	<h2>Metal</h2>
        	Metal can be used in both slow-slope and steep-slope roofs. Metal roofing products can be categorized into two: panels and shingles. There are many types of metal panel slopes and configuration. For traditional roofs such as wood shakes, shingles and tiles, metal shingles are intended to simulate them. Metal roofs have other advantages such as longevity, relative light weight, greater resistance to adverse weather and aesthetically pleasing. Some are rated Class A.<br/><br/>
        	Also, traditional roof coverings such as dete, wood shingles and shakes can be simulated by synthetic roofing products.<br/><br/>
        	But they do not have the same properties.<br/><br/>
        	Due to the above, NRCA recommends that prior to decision on which type of roof to buy the house or building owner look at full-size samples of the product and go over brochures.<br/><br/>
        	It is also useful if the owner visits a building that has a roof of a particular type of material.<br/><br/> 

			<h2>Importance of Ventilation and Insulation</h2>
        	Proper ventilation is an important consideration in the durability of roof systems. A lot of unlivable effects can result from poor ventilation to include shingles that buckle, ineffectiveness of insulation and rotting rafters and sheathing. These occur as heat and moisture build-up in attic. To avoid such disadvantageous results, it is critical not to block off sources of roof ventilation. These sources include louvers, ridge, vents or soffit vents, even during the winter season. In addition, proper ventilation in the attic will help in preventing structural damage due to moisture. It will also increase the life of the roofing materials, reduce the consumption of energy and, more significantly increase the comfort of rooms in the vicinity of the attic.<br/><br/> 
        	Insulation is also essential because it facilitates the free flow of air and plays an important role in achieving proper ventilation. 
        	<br/><br/>
        	Therefore, an ideal attic must have:
			<ul class="content-ul">
				<li>A layer of insulation on the attic floor that does not a gap so as to protect the area below it from heat gain or loss.</li> 
                <li>Next to the ceiling, a vapor retractor under the insulation to stop moisture from going up to the attic.</li>
                <li>Space which are open and vented to promote the free flow of air.</li>
                <li>A gap of not less than one inch between the insulation and the roof sheathing.</li>
			</ul>
			<br/><br/>
        	The requirements for the proper ventilation of attics are not uniform across states. They depend on the specific location of the home or building. This variability is also dependent on the condition of the structure such as its exposure to the sun, shade and atmospheric humidity.<br/><br/>
			However, the general formula is that ventilation is based on the length and width of the attic. NRCA’s recommendation is for every 150 square feet of attic floor there must be a minimum of one square foot of free vent area. The vents must be placed proportionally at the eaves (such as soffits) and at or near the ridge.
        	
        </div>
    </div>
</section>