<?php $this->headTitle("Thank You"); ?>

<section>
    <div class="page">
        <div class="content-outer">
            <h1>Thank you for contacting us.</h1>
             <div class="content section group">
                <div class="col col-left">
                    You are very important to us, all information received will always remain confidential. We will contact you as soon as we review your message.
                    <br/><br/>
                    <!-- Google Code for contact us Conversion Page -->
                    <script type="text/javascript">
                    /* <![CDATA[ */
                    var google_conversion_id = 985137670;
                    var google_conversion_language = "en";
                    var google_conversion_format = "3";
                    var google_conversion_color = "ffffff";
                    var google_conversion_label = "65BRCJqO92QQhoTg1QM";
                    var google_remarketing_only = false;
                    /* ]]> */
                    </script>
                    <script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
                    </script>
                    <noscript>
                    <div style="display:inline;">
                    <img height="1" width="1" style="border-style:none;" alt="" src="//www.googleadservices.com/pagead/conversion/985137670/?label=65BRCJqO92QQhoTg1QM&amp;guid=ON&amp;script=0"/>
                    </div>
                    </noscript>
                                        
                </div>
            </div>
        </div>
    </div>
</section>