<?php $this->headTitle("Settings") ?>

<div class="adminmenuwrap">
	<?=$this->adminNavigation('settings', 'email', $this->basepath("/"));?>
</div>

<div class="content">
    <div class="body">
        <div class="body-content" tabindex="0" style="overflow: hidden;">
            <div class="wrap">
                <h2>Emails</h2> 
                <div class="col-container">                     
                    <div class="col-left">
                    <?php 
                        if($this->flashmessenger()->hasMessages()) :
                            echo '<div class="message">'.$this->flashmessenger()->render().'</div>';
                        endif;
                     
                        $form = $this->form;
                        $form->setAttribute('action', $this->url('settings', array('action'=>'email')));
                        $form->prepare();
                        echo $this->form()->openTag($form);
                    ?>
                    <table class="form-table">  
            		<tbody>    
            		  <tr class="form-field form-required">
            			<th scope="row"><label for="name">Email</label></th> 
            			<td><?=$this->formRow($form->get('email_1'))?>
            			<p class="description">This email receive all messages.</p></td>
            		  </tr>
            		  <tr class="form-field form-required"> 
            			<th scope="row"></th>
            			<td><?=$this->formRow($form->get('submit'))?></td>
            		  </tr>
            		 </tbody>
            		</table> 
            		<?php
            		  echo $this->form()->closeTag();
            		?>  
            		</div>
                </div>
            </div>
        </div>
    </div>
</div>