<?php $this->headTitle("Dashboard")?>

<div class="adminmenuwrap">
	<?=$this->adminNavigation('dashboard', '', $this->basepath("/"));?>
</div>


<!-- Step 1: Create the containing elements. -->

<div class="content">
    <div class="body">
        <div class="body-content" tabindex="0">
            <section id="auth-button"></section>
            <section id="view-selector"></section>
            <section id="timeline"></section>
        </div>
    </div>
</div>

<!-- Step 2: Load the library. -->

<script>
(function(w,d,s,g,js,fjs){
  g=w.gapi||(w.gapi={});g.analytics={q:[],ready:function(cb){this.q.push(cb)}};
  js=d.createElement(s);fjs=d.getElementsByTagName(s)[0];
  js.src='https://apis.google.com/js/platform.js';
  fjs.parentNode.insertBefore(js,fjs);js.onload=function(){g.load('analytics')};
}(window,document,'script'));
</script>

<script>
gapi.analytics.ready(function() {

  // Step 3: Authorize the user.
	  
  var CLIENT_ID = '716557369707-mk7fee72dbhgqkkmp2jsaug4ra1mlapu.apps.googleusercontent.com';

  gapi.analytics.auth.authorize({
    container: 'auth-button',
    clientid: CLIENT_ID,
  });
  /*
	gapi.analytics.auth.authorize({
		  container: 'auth-button',
		  scopes: ['https://www.googleapis.com/auth/analytics.manage.users'],
		  serverAuth: {
		    access_token: 'ye6orv2F-1npMW3u9suM3a7C5Bo/7syv7kUaeTT_hntLJUbMcRfOHLg'
		  }
		});
	*/	
  // Step 4: Create the view selector.

  var viewSelector = new gapi.analytics.ViewSelector({
    container: 'view-selector'
  });

  // Step 5: Create the timeline chart.

  var timeline = new gapi.analytics.googleCharts.DataChart({
    reportType: 'ga',
    query: {
      'dimensions': 'ga:date',
      'metrics': 'ga:sessions',
      'start-date': '30daysAgo',
      'end-date': 'yesterday',
    },
    chart: {
      type: 'LINE',
      container: 'timeline'
    }
  });

  // Step 6: Hook up the components to work together./*
  
  gapi.analytics.auth.on('success', function(response) {
    viewSelector.execute();
  });

/*  viewSelector.execute(); */
  
  viewSelector.on('change', function(ids) {
    var newIds = {
      query: {
        ids: ids
      }
    }
    timeline.set(newIds).execute();
  });
  
});
</script>