<?php $this->headTitle("Widgets > Slogan") ?>

<div class="adminmenuwrap">
	<?=$this->adminNavigation('widgets', 'slogan', $this->basepath("/"));?>
</div>

<div class="content">
    <div class="body">
        <div class="body-content" tabindex="0" style="overflow: hidden;">
            <div class="wrap">
                <h2>Slogan</h2>
                <?php 
                    if($this->flashmessenger()->hasMessages()) :
                        echo '<div class="message">'.$this->flashmessenger()->render().'</div>';
                    endif;
                 
                    $form = $this->form;
                    $form->setAttribute('action', $this->url('widgets', array("action"=>"slogan")));
                    $form->prepare();
                    echo $this->form()->openTag($form);
                ?>
                <table class="form-table">
        		<tbody>
        		  <tr class="form-field form-required">
        			<th scope="row"><label for="name">Slogan</label></th>
        			<td><?=$this->formRow($form->get('slogan'))?>
        			<p class="description">Slogan appears on your home page.</p></td>
        		  </tr>
        		  <tr class="form-field form-required">
        			<th scope="row"><label for="name">Video</label></th>
        			<td><?=$this->formRow($form->get('video'))?>
        			<p class="description">Video appears on your home page.</p></td>
        		  </tr>
        		  <tr class="form-field form-required">
        			<th scope="row"></th>
        			<td><?=$this->formRow($form->get('submit'))?></td>
        		  </tr>
        		 </tbody>
        		</table>
        		<?php
        		  echo $this->form()->closeTag();
        		?>
            </div>
        </div>
    </div>
</div>