<?php $this->headTitle("Edit Category")?>

<div class="adminmenuwrap">
	<?=$this->adminNavigation('gallery', 'category', $this->basepath("/"));?>
</div>
 
<div class="content">
    <div class="body">
        <div class="body-content" tabindex="0" style="overflow: hidden;">
            <div class="wrap">
                <h2>Edit Category</h2>
                <?php
                	$form = $this->form;
                	$form->setAttribute('action', $this->url('gallery', array("action"=>"category-main-edit","id"=>$this->id))); 
                	$form->prepare();
                	echo $this->form()->openTag($form);
                ?>
                <table class="form-table">
        		<tbody>
            		  
            		  <?php // this is for product image
                		  if($this->category->image != '') :
                		  ?>
                		  <tr class="form-required">
                			<th scope="row"><label for="name">Current Image</label></th>
                			<td><img src="<?=$this->basepath('/media/'.$this->config['website']['media'].'/gallery/'.$this->category->image)?>" />
                			<p class="description">Current image for your category.</p></td>
                		  </tr>
                		  <?php 
                		  endif;
            		  ?>
        		  
        		  <tr class="form-required">
        			<th scope="row"><label for="name">Image</label></th>
        			<td><?=$this->formRow($form->get('image'))?>
        			<p class="description">Add image for your category.</p></td>
        		  </tr>
        		  <tr class="form-field form-required">
        			<th scope="row"><label for="name">Name</label></th>
        			<td><?=$this->formRow($form->get('name'))?>
        			<p class="description">The name is how it appears on your site.</p></td>
        		  </tr>
        		  <tr class="form-field form-required">
        			<th scope="row"><label for="name">Description</label></th>
        			<td><?=$this->formRow($form->get('description'))?>
        			<p class="description">Description for your product category.</p></td>
        		  </tr>
        		  <tr class="form-field form-required">
        			<th scope="row"><label for="name">Slug</label></th>
        			<td><?=$this->formRow($form->get('slug'))?>
        			<p class="description">The "slug" is the URL-friendly version of the name. It is usually all lowercase and contains only letters, numbers, and hyphens.</p></td>
        		  </tr>
        		  <tr class="form-field form-required">
        			<th scope="row"><label for="name">Position</label></th>
        			<td><?=$this->formRow($form->get('position'))?>
        			<p class="description">Category order in your cart.</p></td>
        		  </tr>
        		  <tr class="form-field form-required">
        			<th scope="row"></th>
        			<td><?=$this->formRow($form->get('submit'))?></td>
        		  </tr>
        		 </tbody>
        		</table>
        		<input type="hidden" name="parent" value="0">
        		<?php 
        		echo $this->formRow($form->get('category_id'));
        		echo $this->form()->closeTag();
        		?>
            </div>
        </div>
    </div>
</div>