<?php $this->headTitle("Photos") ?>

<div class="adminmenuwrap">
	<?=$this->adminNavigation('gallery', 'index', $this->basepath("/"));?>
</div>

<div class="content">
    <div class="body">
        <div class="body-content" tabindex="0" style="overflow: hidden;">
            <div class="wrap">
                <h2>Picture</h2>
                <?php 
                    if($this->flashmessenger()->hasMessages()) :
                        echo '<div class="message">'.$this->flashmessenger()->render().'</div>';
                    endif;
                ?>
                <div class="col-container">                    
                    <div class="col-right">
                        <table class="list-table widefat fixed tags">
                            <thead>
                                <tr><th class="cb"></th>
                                    <th class="">Category</th>
                                    <th class="">Default Picture</th>
                                    <th class="name">Title</th>
                                    <th>Pictures</th>
                                    <th class="">Position</th>
                                </tr>
                             </thead><?php $this->basepath()?>
                             <tbody>
                             <?php
                             $form_delete = $this->form_delete;
                             $form_delete->setAttribute('action', $this->url('gallery'));
                             $form_delete->prepare();
                             
                             echo $this->form()->openTag($form_delete);            
                             echo '<div class="bulkaction">';
                                 echo $this->formRow($form_delete->get('bulk_actions'));
                                 echo $this->formSubmit($form_delete->get('submit'));
                             echo '</div>';
                             
                             foreach ($this->root_categories as $rcv) :
                                $rc[$rcv->category_id] = array('name' => $rcv->name, 'slug' => $rcv->slug, 'category_id' => $rcv->category_id, 'parent' => $rcv->parent, 'position' => $rcv->position);
                             endforeach;
                            
                             if(count($this->category)>0) :
                                 foreach ($this->category as $cv) : // list subcategories
                                    $cc[] = array('name' => $cv->name, 'slug' => $cv->slug, 'category_id' => $cv->category_id, 'parent' => $cv->parent, 'position' => $cv->position);
                                 endforeach;
                             else :
                                $cc = '';
                             endif;

                             $i = array(); $s = array(); // s = picture default image
                             
                             foreach ($this->gallery as $pv) : // load gallery
                                if($pv->variation == 0) :
                                    $pp[$pv->id] = array('id' => $pv->id, 'position' => $pv->position, 'name' => $pv->name, 'variation' => $pv->variation);
                                else : // get variation of product
                                    if(isset($i[$pv->variation])) :
                                        $i[$pv->variation] = $i[$pv->variation] + 1;
                                    else :
                                        $i[$pv->variation] = 1;
                                        $s[$pv->variation] = $pv->image;
                                    endif;
                                endif;
                             endforeach;
                                                          
                             foreach ($this->cat_rel as $krv) : // list category and product relatonships
                                $kr[$krv->gallery_id] = array('gallery_id' => $krv->gallery_id, 'category_id' => $krv->category_id, 'category_name' => $rc[$krv->category_id]['name']);
                             endforeach;

                             $tt = array();
                             
                             foreach ($rc as $fl) :
                                echo '<tr class="alternate"><td></td><td colspan="5"><h3>'.$fl['name'].'</h3></td></tr>';
                             
                                foreach ($kr as $fr) : // sort
                                    if($fl['category_id'] == $fr['category_id']) :
                                        $tt[$fr['gallery_id']] = $pp[$fr['gallery_id']]['position'];
                                    endif;
                                endforeach;
                                if(isset($tt) && count($tt) > 0) : // check for empty categories
                                    asort($tt); // sort position value
                                    foreach($tt as $t => $b) :
                                        echo '<tr class="alternate">
                                                  <td class="cb"><input type="checkbox" name="cb[]" value="'.$pp[$t]['id'].'" /></td>
                                                  <td>'.$kr[$pp[$t]['id']]['category_name'].'</td>
                                                  <td><a href="'.$this->url('gallery', array("action"=>"edit","id"=>$pp[$t]['id'])).'"><img src="'.$this->basepath('media/'.$this->config['website']['media'].'/gallery/'.$s[$pp[$t]['id']]).'" style="height: 88px;"></a><input type="hidden" name="file['.$pp[$t]['id'].']" value="'.$s[$pp[$t]['id']].'" /></td>
                                                  <td><a class="row-title" href="'.$this->url('gallery', array("action"=>"edit","id"=>$pp[$t]['id'])).'">'.$pp[$t]['name'].'</a></td>
                                                  <td><a class="row-title" href="'.$this->url('gallery', array("action"=>"variations","id"=>$pp[$t]['id'])).'">Add pictures</a> ('.$i[$pp[$t]['id']].')</td>
                                                  <td>'.$pp[$t]['position'].'</td>
                                              </tr>';
                                    endforeach;
                                    unset($tt);
                                endif;
                             endforeach;
        
                             ?>
                             </tbody>
                             <tfoot>
                                <tr><th class="cb"></th>
                                    <th class="">Default Image</th>
                                    <th class="name">Title</th>
                                    <th class="">Pictures</th>
                                    <th class="">Description</th>
                                    <th class="">Position</th>
                                </tr>
                             </tfoot>
                        </table>  
                        <?php 
                            echo '<div class="bulkaction">';
                            echo $this->formRow($form_delete->get('bulk_actions'));
                            echo $this->formRow($form_delete->get('bulk_action'));
                            echo $this->formSubmit($form_delete->get('submit'));
                            echo '</div>';
                            echo $this->form()->closeTag();
                        ?>  
                    </div>
                    
                    <div class="col-left">
                        <div class="col-wrap">
                            <div class="form-wrap">
                                <h3>Add New Pricture</h3>
                                <?php
                                	$form_add = $this->form_add;
                                	$form_add->setAttribute('action', $this->url('gallery')); 
                                	$form_add->prepare();
                                	echo $this->form()->openTag($form_add);
                                ?>
                                  
                                <?=$this->formRow($form_add->get('image'))?>
                                <p>Picture for your gallery.</p>
                                  
                                <?=$this->formRow($form_add->get('name'))?>
                                <p>Title for your picture.</p>
                                                                
                                <?=$this->formRow($form_add->get('description'))?>
                                <p>Description appears under picture.</p>
                                
                                <?=$this->formRow($form_add->get('category_id'))?>
                                <p>Default category for your picture.</p>
                                
                                <?=$this->formRow($form_add->get('position'))?>
                                <p>Picture position in gallery.</p>
                                    
                                <?php
                                	echo $this->formSubmit($form_add->get('submit'));
                                	echo $this->form()->closeTag();
                            	?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
$(document).ready(
	function()
	{
		$( ".bulk_actions" ).change(function() // bulk actions 
		{
			$("#bulk_action").val($(this).val());	 
		}); 	
	}
);
</script>