<?php $this->headTitle("Category")?>

<div class="adminmenuwrap">
   	<?=$this->adminNavigation('posts', 'category', $this->basepath("/"));?>
</div>

<div class="content">
    <div class="body">
        <div class="body-content" tabindex="0" style="overflow: hidden;">
            <div class="wrap">
                <h2>Categories</h2>
                <?php 
                    if($this->flashmessenger()->hasMessages()) :
                        echo '<div class="message">'.$this->flashmessenger()->render().'</div>';
                    endif;
                ?>
                <div class="col-container">                    
                    <div class="col-right">
                        <table class="list-table widefat fixed tags">
                            <thead>
                                <tr><th class="cb"></th>
                                    <th class="name">Name</th>
                                    <th class="">Slug</th>
                                    <th class="">Posts</th>
                                </tr>
                             </thead>
                             <tbody>
                             <?php
                             $form_delete = $this->form_delete;
                             $form_delete->setAttribute('action', $this->url('posts', array("action"=>"category")));
                             $form_delete->prepare();
                             
                             echo $this->form()->openTag($form_delete);            
                             echo '<div class="bulkaction">';
                                 echo $this->formRow($form_delete->get('bulk_actions'));
                                 echo $this->formSubmit($form_delete->get('submit'));
                             echo '</div>';
                             foreach ($this->category as $cat) : // sort
                                 if ($cat->parent == 0) :
                                 	    $category_list[$cat->category_id] = array('name' => $cat->name, 'slug' => $cat->slug);
                                 else : // load sub categories
                                        $category_list[$cat->parent]['list'][$cat->category_id]['name'] = $cat->name;
                                        $category_list[$cat->parent]['list'][$cat->category_id]['slug'] = $cat->slug;
                                        $category_list[$cat->parent]['list'][$cat->category_id]['category_id'] = $cat->category_id;
                                 endif; // $cat->parent   
                             endforeach;
                             
                             foreach ($category_list as $cl) : // load html                               
                                echo '<tr class="alternate"><td></td><td class="row-title">'.$cl['name'].'</td><td>'.$cl['slug'].'</td><td></td></tr>';                                
                                if(is_array($cl['list'])) :
                                    foreach($cl['list'] as $list) : // load sub categories
                                        $count = (isset($this->cat_count[$list['category_id']])) ? count($this->cat_count[$list['category_id']]) : 0;
                                        echo '<tr class="alternate"><td class="cb"><input type="checkbox" name="cb[]" value="'.$list['category_id'].'" /></td><td> <a class="row-title" href="'.$this->url('posts', array("action"=>"category-edit","id"=>$list['category_id'])).'">&#9472; &nbsp; '.$list['name'].'</td><td>'.$list['slug'].'</a></td><td>'.$count.'</td></tr>';
                                    endforeach;
                               else :
                                    echo '<tr class="alternate"><td></td><td>Please add category</td><td></td><td></td></tr>';
                               endif;
                             endforeach;
                             
                             ?>
                             </tbody>
                             <tfoot>
                                <tr><th class="cb"></th>
                                    <th class="name">Name</th>
                                    <th class="">Slug</th>
                                    <th class="">Posts</th>
                                </tr>
                             </tfoot>
                        </table>  
                        <?php 
                            echo '<div class="bulkaction">';
                            echo $this->formRow($form_delete->get('bulk_actions'));
                            echo $this->formRow($form_delete->get('bulk_action'));
                            echo $this->formSubmit($form_delete->get('submit'));
                            echo '</div>';
                            echo $this->form()->closeTag();
                        ?>  
                    </div>
                    
                    <div class="col-left">
                        <div class="col-wrap">
                            <div class="form-wrap">
                                <h3>Add New Category</h3>
                                <?php
                                	$form_add = $this->form_add;
                                	$form_add->setAttribute('action', $this->url('posts', array("action"=>"category"))); 
                                	$form_add->prepare();
                                	echo $this->form()->openTag($form_add);
                                ?>
                                    
                                <?=$this->formRow($form_add->get('name'))?>
                                <p>The name is how it appears on your site.</p>
                                
                                <?=$this->formRow($form_add->get('slug'))?>
                                <p>The "slug" is the URL-friendly version of the name. It is usually all lowercase and contains only letters, numbers, and hyphens.</p>
                                
                                <?=$this->formRow($form_add->get('parent'))?>
                                <p>Categories have a hierarchy. You might have a Jazz category, and under that have children categories for Bebop and Big Band. Totally optional.</p>
                                    
                                <?php
                                	echo $this->formSubmit($form_add->get('submit'));
                                	echo $this->form()->closeTag();
                            	?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
$(document).ready(
	function()
	{
		$( ".bulk_actions" ).change(function() // bulk actions 
		{
			$("#bulk_action").val($(this).val());	 
		}); 	
	}
);
</script>