<?php 
header('Content-Type: application/json');

$dir    = './public/media/'.$this->config['website']['media'].'/img';
$files = scandir($dir);

$count = count($files);
$c = 0;
$html = '[';
foreach (scandir($dir) as $file) :    
        if (!in_array($file,array(".",".."))) :
            if($c !== ($count-1)){$p=',';}else{$p='';} 
            $html .= '{ "thumb": "http://cms.'.$this->config['website']['uri'].'/media/'.$this->config['website']['media'].'/img/'.$file.'", "image": "http://cms.'.$this->config['website']['uri'].'/media/'.$this->config['website']['media'].'/img/'.$file.'", "title": "", "title": "" }'.$p;
        endif;
        $c++;
endforeach;
$html .= ']';

echo $html;
?>