<?php $this->headTitle("Edit Category")?>

<div class="adminmenuwrap">
	<?=$this->adminNavigation('products', 'category', $this->basepath("/"));?>
</div>

<div class="content">
    <div class="body">
        <div class="body-content" tabindex="0" style="overflow: hidden;">
            <div class="wrap">
                <h2>Edit Category</h2>
                <?php
                	$form = $this->form;
                	$form->setAttribute('action', $this->url('products', array("action"=>"category-edit","id"=>$this->id))); 
                	$form->prepare();
                	echo $this->form()->openTag($form);
                ?>
                <table class="form-table">
        		<tbody>
        		  <tr class="form-field form-required">
        			<th scope="row"><label for="name">Name</label></th>
        			<td><?=$this->formRow($form->get('name'))?>
        			<p class="description">The name is how it appears on your site.</p></td>
        		  </tr>
        		  <tr class="form-field form-required">
        			<th scope="row"><label for="name">Slug</label></th>
        			<td><?=$this->formRow($form->get('slug'))?>
        			<p class="description">The "slug" is the URL-friendly version of the name. It is usually all lowercase and contains only letters, numbers, and hyphens.</p></td>
        		  </tr>
        		  <tr class="form-field form-required">
        			<th scope="row"><label for="name">Parent</label></th>
        			<td><?=$this->formRow($form->get('parent'))?>
        			<p class="description">Categories have a hierarchy. You might have a Jazz category, and under that have children categories for Bebop and Big Band. Totally optional.</p></td>
        		  </tr>
        		  <tr class="form-field form-required">
        			<th scope="row"><label for="name">Position</label></th>
        			<td><?=$this->formRow($form->get('position'))?>
        			<p class="description">Category order in your cart.</p></td>
        		  </tr>         
        		  <tr class="form-field form-required">
        			<th scope="row"></th>
        			<td><?=$this->formRow($form->get('submit'))?></td>
        		  </tr>
        		 </tbody>
        		</table>
        		<?php 
        		echo $this->formRow($form->get('category_id'));
        		echo $this->form()->closeTag();
        		?>
            </div>
        </div>
    </div>
</div>