<?php $this->headTitle("Products") ?>

<div class="adminmenuwrap">
	<?=$this->adminNavigation('products', 'index', $this->basepath("/"));?>
</div>

<div class="content">
    <div class="body">
        <div class="body-content" tabindex="0" style="overflow: hidden;">
            <div class="wrap">
                <h2>Products</h2>
                <?php 
                    if($this->flashmessenger()->hasMessages()) :
                        echo '<div class="message">'.$this->flashmessenger()->render().'</div>';
                    endif;
                ?>
                <div class="col-container">                    
                    <div class="col-right">
                        <table class="list-table widefat fixed tags">
                            <thead>
                                <tr><th class="cb"></th>
                                    <th class="">Category</th>
                                    <th class="">Image</th>
                                    <th class="name">Title</th>
                                    <th>Variations</th>
                                    <th class="">Position</th>
                                </tr>
                             </thead><?php $this->basepath()?>
                             <tbody>
                             <?php
                             $form_delete = $this->form_delete;
                             $form_delete->setAttribute('action', $this->url('products'));
                             $form_delete->prepare();
                             
                             echo $this->form()->openTag($form_delete);            
                             echo '<div class="bulkaction">';
                                 echo $this->formRow($form_delete->get('bulk_actions'));
                                 echo $this->formSubmit($form_delete->get('submit'));
                             echo '</div>';
                             
                             foreach ($this->root_categories as $rcv) :
                                $rc[] = array('name' => $rcv->name, 'slug' => $rcv->slug, 'category_id' => $rcv->category_id, 'parent' => $rcv->parent, 'position' => $rcv->position);
                             endforeach;
                            
                             if(count($this->category)>0) :
                                 foreach ($this->category as $cv) : // list subcategories
                                    $cc[] = array('name' => $cv->name, 'slug' => $cv->slug, 'category_id' => $cv->category_id, 'parent' => $cv->parent, 'position' => $cv->position);
                                 endforeach;
                             else :
                                $cc = '';
                             endif;

                             $i = array();
                             
                             foreach ($this->products as $pv) : // load products
                                if($pv->variation == 0) :
                                    $pp[] = array('id' => $pv->id, 'image' => $pv->image, 'position' => $pv->position, 'name' => $pv->name, 'variation' => $pv->variation);
                                else : // get variation of product
                                    if(isset($i[$pv->variation])) :
                                        $i[$pv->variation] = $i[$pv->variation] + 1;
                                    else :
                                        $i[$pv->variation] = 1;
                                    endif;
                                endif;
                             endforeach;
                                                          
                             foreach ($this->cat_rel as $krv) : // list category and product relatonships
                                $kr[] = array('product_id' => $krv->product_id, 'category_id' => $krv->category_id);
                             endforeach;
                             
                             
                             foreach ($pp as $p) :
                                 echo '<tr class="alternate">
                                        <td class="cb"><input type="checkbox" name="cb[]" value="'.$p['id'].'" /></td>
                                        <td>'. $p['name'].'</td>
                                        <td><a href="'.$this->url('products', array("action"=>"edit","id"=>$p['id'])).'"><img src="'.$this->basepath('media/'.$this->config['website']['media'].'/product/'.$p['image']).'" style="height: 88px;"></a><input type="hidden" name="file['.$p['id'].']" value="'.$p['image'].'" /></td>
                                        <td><a class="row-title" href="'.$this->url('products', array("action"=>"edit","id"=>$p['id'])).'">'.$p['name'].'</a></td><td><a class="row-title" href="'.$this->url('products', array("action"=>"variations","id"=>$p['id'])).'">'.$i[$p['id']].'</a></td><td>'.$p['position'].'</td></tr>';
                             endforeach;
                                         
                             /*
                             foreach ($rc as $r) :
                                    // echo $r['name'].'<br/>';
                                    foreach ($kr as $k) : // get root products
                                        if($r['category_id'] == $k['category_id']) :
                                            foreach ($pp as $p) :
                                                if($k['product_id'] == $p['id']) :
                                                    //echo $k['product_id'] .' and '. $p['id'].'<br/>';
                                                    // echo $r['name'].' > ' .$p['product_name'].'<br/>';
                                                    echo '<tr class="alternate">
                                                            <td class="cb"><input type="checkbox" name="cb[]" value="'.$p['id'].'" /></td>
                                                            <td>'. $r['name'].'</td>
                                                            <td><a href="'.$this->url('products', array("action"=>"edit","id"=>$p['id'])).'"><img src="'.$this->basepath('media/'.$this->config['website']['media'].'/product/'.$p['image']).'" style="height: 88px;"></a><input type="hidden" name="file['.$p['id'].']" value="'.$p['image'].'" /></td>
                                                            <td><a class="row-title" href="'.$this->url('products', array("action"=>"edit","id"=>$p['id'])).'">'.$p['name'].'</a></td><td><a class="row-title" href="'.$this->url('products', array("action"=>"variations","id"=>$p['id'])).'">variations</a></td><td>'.$p['position'].'</td></tr>';
                                                endif;
                                            endforeach;
                                        endif;
                                    endforeach;
                                    
                                    if(is_array($cc)) :
                                        foreach ($cc as $c) : // get products sub categories
                                            if($r['category_id'] == $c['parent']) :
                                                // echo $r['name'].' > '.$c['name'].'<br/>';
                                                foreach ($kr as $k) :
                                                    if($c['category_id'] == $k['category_id']) :
                                                        foreach ($pp as $p) :
                                                            if($k['product_id'] == $p['id']) :
                                                                //echo $k['product_id'] .' and '. $p['id'].'<br/>';
                                                                // echo $r['name'].' > '.$c['name'].' > '.$p['product_name'].'<br/>';
                                                                echo '<tr class="alternate">
                                                                        <td class="cb"><input type="checkbox" name="cb[]" value="'.$p['id'].'" /></td>
                                                                        <td>'. $r['name'].' > '.$c['name'].'</td>
                                                                        <td><a href="'.$this->url('products', array("action"=>"edit","id"=>$p['id'])).'"><img src="'.$this->basepath('media/'.$this->config['website']['media'].'/product/'.$p['image']).'" style="height: 88px;"></a><input type="hidden" name="file['.$p['id'].']" value="'.$p['image'].'" /></td>
                                                                        <td><a class="row-title" href="'.$this->url('products', array("action"=>"edit","id"=>$p['id'])).'">'.$p[''].'</a></td><td><a class="row-title" href="'.$this->url('products', array("action"=>"variations","id"=>$p['id'])).'">variations</a></td><td>'.$p['position'].'</td></tr>';
                                                            endif;
                                                        endforeach;
                                                    endif;
                                                endforeach;
                                            endif;
                                        endforeach;
                                    endif;
                             endforeach;
                             
                             
                             /*
                            $sub = '';
                            foreach ($this->root_categories as $l) :
                                // count sub categories ... if no sub category then we can allow to delete
                                foreach ($cs as $s) :
                                    if($l->category_id == $s['parent']) :
                                        $sub .= '<tr class="alternate"><td></td><td> <a class="row-title" href="'.$this->url('products', array("action"=>"category-edit","id"=>$s['category_id'])).'">&#9472; &nbsp; '.$s['name'].'</td><td>'.$s['slug'].'</a></td><td>0</td><td>'.$s['position'].'</td></tr>';
                                        foreach ($pr as $p) : // load products
                                            if($p['id'] == $s['parent']):
                                                $sub .= '<tr class="alternate">
                                                            <td class="cb"><input type="checkbox" name="cb[]" value="'.$p['id'].'" /></td>
                                                            <td><a href="'.$this->basepath('media/'.$this->config['website']['media'].'/products/'.$p['image']).'"><img src="'.$this->basepath('media/'.$this->config['website']['media'].'/product/'.$p['image']).'"></a><input type="hidden" name="file['.$p['id'].']" value="'.$p['image'].'" /></td>
                                                            <td><a class="row-title" href="'.$this->url('products', array("action"=>"edit","id"=>$p['id'])).'">'.$p['product_name'].'</a></td><td>'.$p['position'].'</td></tr>';
                                            endif;
                                        endforeach;
                                    endif;
                                endforeach;
                                if($sub == '') :
                                    echo '<tr class="alternate"><td></td><td class="row-title"><a class="row-title" href="'.$this->url('products', array("action"=>"category-main-edit","id"=>$l->category_id)).'">'.$l->name.'</a></td><td>'.$l->slug.'</td><td></td><td>'.$l->position.'</td></tr>';
                                    
                                    foreach ($pr as $p) : // load products
                                        echo $p['id'].',';
                                        foreach ($cr as $c) :
                                            if($c->category_id == $l->category_id):
                                                echo '<tr class="alternate">
                                                        <td class="cb"><input type="checkbox" name="cb[]" value="'.$p['id'].'" /></td>
                                                        <td><a href="'.$this->basepath('media/'.$this->config['website']['media'].'/products/'.$p['image']).'"><img src="'.$this->basepath('media/'.$this->config['website']['media'].'/product/'.$p['image']).'"></a><input type="hidden" name="file['.$p['id'].']" value="'.$p['image'].'" /></td>
                                                        <td><a class="row-title" href="'.$this->url('products', array("action"=>"edit","id"=>$p['id'])).'">'.$p['product_name'].'</a></td><td>'.$p['position'].'</td></tr>';
                                            endif;
                                        endforeach;
                                    endforeach;
                                else :
                                    echo '<tr class="alternate"><td></td><td class="row-title"><a class="row-title" href="'.$this->url('products', array("action"=>"category-main-edit","id"=>$l->category_id)).'">'.$l->name.'</a></td><td>'.$l->slug.'</td><td></td><td>'.$l->position.'</td></tr>';
                                    echo $sub;
                                endif;
                                $sub = '';
                             endforeach;
                             /*
                             foreach ($this->products as $p) : // load products
                                    echo '<tr class="alternate">
                                            <td class="cb"><input type="checkbox" name="cb[]" value="'.$p->id.'" /></td>
                                            <td><a href="'.$this->basepath('media/'.$this->config['website']['media'].'/products/'.$p->image).'"><img src="'.$this->basepath('media/'.$this->config['website']['media'].'/product/'.$p->image).'"></a><input type="hidden" name="file['.$p->id.']" value="'.$p->image.'" /></td>
                                            <td><a class="row-title" href="'.$this->url('products', array("action"=>"edit","id"=>$p->id)).'">'.$p->product_name_2.'</a></td><td>'.$p->description.'</td><td>'.$p->position.'</td></tr>';
                             endforeach;
                             */
                             ?>
                             </tbody>
                             <tfoot>
                                <tr><th class="cb"></th>
                                    <th class="">Image</th>
                                    <th class="name">Title</th>
                                    <th class="">Variations</th>
                                    <th class="">Description</th>
                                    <th class="">Position</th>
                                </tr>
                             </tfoot>
                        </table>  
                        <?php 
                            echo '<div class="bulkaction">';
                            echo $this->formRow($form_delete->get('bulk_actions'));
                            echo $this->formRow($form_delete->get('bulk_action'));
                            echo $this->formSubmit($form_delete->get('submit'));
                            echo '</div>';
                            echo $this->form()->closeTag();
                        ?>  
                    </div>
                    
                    <div class="col-left">
                        <div class="col-wrap">
                            <div class="form-wrap">
                                <h3>Add New Product</h3>
                                <?php
                                	$form_add = $this->form_add;
                                	$form_add->setAttribute('action', $this->url('products')); 
                                	$form_add->prepare();
                                	echo $this->form()->openTag($form_add);
                                ?>
                                  
                                <?=$this->formRow($form_add->get('image'))?>
                                <p>Image for your product.</p>
                                  
                                <?=$this->formRow($form_add->get('name'))?>
                                <p>Friendly Name for your checkout and email.</p>
                                
                                <?=$this->formRow($form_add->get('price'))?>
                                <p>Product price.</p>
                                
                                <?=$this->formRow($form_add->get('qty'))?>
                                <p>Product quantity. Use -1 for unlimited supply.</p>
                                
                                <?=$this->formRow($form_add->get('description'))?>
                                <p>Description appears under prduct name.</p>
                                
                                <?=$this->formRow($form_add->get('category_id'))?>
                                <p>Default category for your product.</p>
                                
                                <?=$this->formRow($form_add->get('position'))?>
                                <p>Product position in cart.</p>
                                
                                <?=$this->formRow($form_add->get('tax'))?>
                                <p>Add tax to your product on checkout?</p>
                                    
                                <?php
                                	echo $this->formSubmit($form_add->get('submit'));
                                	echo $this->form()->closeTag();
                            	?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
$(document).ready(
	function()
	{
		$( ".bulk_actions" ).change(function() // bulk actions 
		{
			$("#bulk_action").val($(this).val());	 
		}); 	
	}
);
</script>