<?php $this->headTitle("Orders")?>
<div class="adminmenuwrap">
	<?=$this->adminNavigation('products', 'orders', $this->basepath("/"));?>
</div>

<div class="content">
    <div class="body">
        <div class="body-content" tabindex="0" style="overflow: hidden;">
            <div class="wrap">
                <div style="float: right;">
                    <?php
                        $form = $this->form;
                        $form->setAttribute('action', $this->url('products', array("action"=>"orders")));
                        $form->prepare();
                        echo $this->form()->openTag($form);
                        echo $this->formRow($form->get('submit'));
                        echo $this->form()->closeTag();
                    ?>
                </div>
                <h2>Orders</h2>
                <?php 
                    if($this->flashmessenger()->hasMessages()) :
                        echo '<div class="message">'.$this->flashmessenger()->render().'</div>';
                    endif;
                ?>
                <div class="col-container">                    
                    
                        <table class="list-table widefat fixed tags">
                            <thead>
                                <tr><th class="cb">#</th>
                                    <th class="name">Customer Name</th>
                                    <th class="">Products</th>
                                    <th class="">Total</th>
                                    <th class="">Date</th>
                                    <th class=""></th>
                                </tr>
                             </thead>
                             <tbody>
	                            <?php 
	                            	$c=0; $cat='';
		                            foreach ($this->orders as $order) : // load html
	                            		if($c==0){$cc='alternate';$c=1;}else{$cc='alternate-2';$c=0;} // change color
			                            echo '<tr class="'.$cc.'"><td class="cb">'.$order->id.'</td><td>'.$order->fname.' '.$order->lname.'</td><td>'.count(json_decode($order->order_items, true)).'</td><td>'.$order->order_amount.'</td><td>'.$order->date.'</td><td><a href="'.$this->basepath('products/order/'.$order->id).'">view order</a></td></tr>';
		                            endforeach;
	                            ?>
                             </tbody>
                             <tfoot>
                                <tr><th class="cb">Order #</th>
                                    <th class="name">Customer Name</th>
                                    <th class="">Products</th>
                                    <th class="">Total</th>
                                    <th class="">Date</th>
                                    <th class=""></th>
                                </tr>
                             </tfoot>
                        </table>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
$(document).ready(
	function()
	{
		$( ".bulk_actions" ).change(function() // bulk actions 
		{
			$("#bulk_action").val($(this).val());	 
		}); 	
	}
);
</script>