<?php $this->headTitle("Edit Product Variation")?>

<div class="adminmenuwrap">
	<?=$this->adminNavigation('products', '', $this->basepath("/"));?>
</div>

<div class="content">
    <div class="body">
        <div class="body-content" tabindex="0" style="overflow: hidden;">
            <div class="wrap">
                <h2>Edit Product Variation</h2>
                <?php
                	$form = $this->form;
                	$form->setAttribute('action', $this->url('products', array("action"=>"variation-edit", "id"=>$this->id))); 
                	$form->prepare();
                	echo $this->form()->openTag($form);
                ?>
                <table class="form-table">
        		<tbody>        		     		  
        		  <tr class="form-field form-required">
        			<th scope="row"><label for="name">Product Name</label></th>
        			<td><?=$this->formRow($form->get('name'))?>
        			<p class="description">Product Name for your checkout and email.</p></td>
        		  </tr>
        		  <tr class="form-field form-required">
        			<th scope="row"><label for="name">Product Price</label></th>
        			<td><?=$this->formRow($form->get('price'))?>
        			<p class="description">Set price for your product.</p></td>
        		  </tr>
        		  <tr class="form-field form-required">
        			<th scope="row"><label for="name">Product Qty</label></th>
        			<td><?=$this->formRow($form->get('qty'))?>
        			<p class="description">Qty for your product.</p></td>
        		  </tr>
        		  <tr class="form-field form-required">
        			<th scope="row"><label for="name">Position</label></th>
        			<td><?=$this->formRow($form->get('position'))?>
        			<p class="description">Product position in cart.</p></td>
        		  </tr>        		 
        		  <tr class="form-field form-required">
        			<th scope="row"></th>
        			<td><?=$this->formRow($form->get('submit'))?></td>
        		  </tr>
        		 </tbody>
        		</table>
        		<?php 
        		  echo $this->form()->closeTag();
        		?>
            </div>
        </div>
    </div>
</div>